"""create users departments dx_tokens tables

Revision ID: 5ebc211a92a1
Revises:
Create Date: 2026-08-20 11:13:22.455766
"""

import sqlalchemy as sa

from alembic import op

revision = "5ebc211a92a1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("departments_pkey")),
    )
    op.create_index(op.f("departments_code_idx"), "departments", ["code"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.Enum("OWNER", "ADMIN", "MEMBER", name="userrole", native_enum=False), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "PENDING", "BLOCKED", name="userstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("external_user_id", sa.String(length=128), nullable=True),
        sa.Column("employee_code", sa.String(length=64), nullable=True),
        sa.Column("email_confirmed", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], name=op.f("users_department_id_fkey"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("users_department_id_idx"), "users", ["department_id"], unique=False)
    op.create_index(op.f("users_email_idx"), "users", ["email"], unique=True)
    op.create_index(op.f("users_external_user_id_idx"), "users", ["external_user_id"], unique=True)
    op.create_index(op.f("users_status_idx"), "users", ["status"], unique=False)
    op.create_table(
        "dx_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scopes", sa.Text(), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("dx_tokens_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("dx_tokens_pkey")),
    )
    op.create_index(op.f("dx_tokens_user_id_idx"), "dx_tokens", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("dx_tokens_user_id_idx"), table_name="dx_tokens")
    op.drop_table("dx_tokens")
    op.drop_index(op.f("users_status_idx"), table_name="users")
    op.drop_index(op.f("users_external_user_id_idx"), table_name="users")
    op.drop_index(op.f("users_email_idx"), table_name="users")
    op.drop_index(op.f("users_department_id_idx"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("departments_code_idx"), table_name="departments")
    op.drop_table("departments")
    # ### end Alembic commands ###
